// GENERATED by scripts/sync-projects.mjs — do not edit by hand.
// Private repositories carry `url: null` so nothing can link to them.

export type Repo = {
  name: string;
  description: string | null;
  language: string | null;
  updatedAt: string;
  isPrivate: boolean;
  stars: number;
  url: string | null;
  homepage: string | null;
};

export const repos: Repo[] = [
  {
    "name": "znapit-backend",
    "description": null,
    "language": "PHP",
    "updatedAt": "2026-07-25",
    "isPrivate": true,
    "stars": 0,
    "url": null,
    "homepage": null
  },
  {
    "name": "csi-esp32-motion-detection",
    "description": "WiFi CSI-Based Motion Detection on a Low-Cost ESP32: Adaptive State-Based Detection with Spearman Correlation. Host-side pipeline, experimental data, and paper.",
    "language": "TeX",
    "updatedAt": "2026-07-23",
    "isPrivate": false,
    "stars": 0,
    "url": "https://github.com/kittyofheaven/csi-esp32-motion-detection",
    "homepage": null
  },
  {
    "name": "Data-Mining-for-Home-Credit-Default-Risk",
    "description": "Data mining (KDD) pipeline on the Home Credit Default Risk dataset — preprocessing, clustering, association rules, and anomaly detection. Dataset: https://www.kaggle.com/competitions/home-credit-default-risk/data",
    "language": "Jupyter Notebook",
    "updatedAt": "2026-07-23",
    "isPrivate": true,
    "stars": 0,
    "url": null,
    "homepage": null
  },
  {
    "name": "MonkeysLimitFE",
    "description": null,
    "language": "JavaScript",
    "updatedAt": "2026-03-07",
    "isPrivate": false,
    "stars": 0,
    "url": "https://github.com/kittyofheaven/MonkeysLimitFE",
    "homepage": null
  },
  {
    "name": "Monkeyslimit",
    "description": null,
    "language": "Kotlin",
    "updatedAt": "2026-03-04",
    "isPrivate": false,
    "stars": 0,
    "url": "https://github.com/kittyofheaven/Monkeyslimit",
    "homepage": null
  },
  {
    "name": "monkeylimitsBackend",
    "description": null,
    "language": "Python",
    "updatedAt": "2026-02-22",
    "isPrivate": false,
    "stars": 0,
    "url": "https://github.com/kittyofheaven/monkeylimitsBackend",
    "homepage": null
  },
  {
    "name": "monkeylimitsML",
    "description": "Project Machine Learning Cawu 4",
    "language": "Jupyter Notebook",
    "updatedAt": "2026-02-21",
    "isPrivate": false,
    "stars": 0,
    "url": "https://github.com/kittyofheaven/monkeylimitsML",
    "homepage": null
  },
  {
    "name": "kaizenbe",
    "description": null,
    "language": "TypeScript",
    "updatedAt": "2025-11-21",
    "isPrivate": false,
    "stars": 0,
    "url": "https://github.com/kittyofheaven/kaizenbe",
    "homepage": null
  },
  {
    "name": "kaizensuper",
    "description": null,
    "language": "TypeScript",
    "updatedAt": "2025-11-20",
    "isPrivate": false,
    "stars": 0,
    "url": "https://github.com/kittyofheaven/kaizensuper",
    "homepage": null
  },
  {
    "name": "kaizenfe",
    "description": null,
    "language": "TypeScript",
    "updatedAt": "2025-11-20",
    "isPrivate": false,
    "stars": 0,
    "url": "https://github.com/kittyofheaven/kaizenfe",
    "homepage": null
  },
  {
    "name": "vivy-f-2.0",
    "description": null,
    "language": "JavaScript",
    "updatedAt": "2025-11-20",
    "isPrivate": false,
    "stars": 0,
    "url": "https://github.com/kittyofheaven/vivy-f-2.0",
    "homepage": null
  },
  {
    "name": "socs1",
    "description": "all codes that i do in cawu 1 as ppti student",
    "language": "C++",
    "updatedAt": "2025-08-13",
    "isPrivate": true,
    "stars": 0,
    "url": null,
    "homepage": null
  },
  {
    "name": "doom-o-clock",
    "description": "Doom o’clock is a website/project that features a countdown of “when will the earth end” and a greenhouse gas effect emission prediction that’s predicted",
    "language": "HTML",
    "updatedAt": "2025-07-10",
    "isPrivate": false,
    "stars": 5,
    "url": "https://github.com/kittyofheaven/doom-o-clock",
    "homepage": "https://doom-o-clock.theohalpern.repl.co/"
  },
  {
    "name": "binus-OOP-UAC-exercise",
    "description": null,
    "language": "Java",
    "updatedAt": "2025-05-30",
    "isPrivate": false,
    "stars": 0,
    "url": "https://github.com/kittyofheaven/binus-OOP-UAC-exercise",
    "homepage": null
  },
  {
    "name": "HCI",
    "description": "Project HCI Lab Cawu 2, PALORANT",
    "language": "CSS",
    "updatedAt": "2025-04-25",
    "isPrivate": false,
    "stars": 0,
    "url": "https://github.com/kittyofheaven/HCI",
    "homepage": null
  },
  {
    "name": "niuniu-backend",
    "description": "niu niu backend",
    "language": "JavaScript",
    "updatedAt": "2025-04-25",
    "isPrivate": false,
    "stars": 0,
    "url": "https://github.com/kittyofheaven/niuniu-backend",
    "homepage": null
  },
  {
    "name": "Restaurant",
    "description": "PPTI OOP 2025",
    "language": "Java",
    "updatedAt": "2025-03-20",
    "isPrivate": false,
    "stars": 0,
    "url": "https://github.com/kittyofheaven/Restaurant",
    "homepage": null
  },
  {
    "name": "binus-OOP-asg2-library",
    "description": null,
    "language": "Java",
    "updatedAt": "2025-02-06",
    "isPrivate": false,
    "stars": 0,
    "url": "https://github.com/kittyofheaven/binus-OOP-asg2-library",
    "homepage": null
  },
  {
    "name": "binus-OOP-asg1-tictactoe",
    "description": null,
    "language": "Java",
    "updatedAt": "2025-02-06",
    "isPrivate": false,
    "stars": 0,
    "url": "https://github.com/kittyofheaven/binus-OOP-asg1-tictactoe",
    "homepage": null
  },
  {
    "name": "STREAMLIT",
    "description": null,
    "language": "Python",
    "updatedAt": "2024-07-11",
    "isPrivate": false,
    "stars": 0,
    "url": "https://github.com/kittyofheaven/STREAMLIT",
    "homepage": null
  },
  {
    "name": "gdp-dashboard-template-ox11ao4izu9",
    "description": null,
    "language": "Python",
    "updatedAt": "2024-07-11",
    "isPrivate": false,
    "stars": 0,
    "url": "https://github.com/kittyofheaven/gdp-dashboard-template-ox11ao4izu9",
    "homepage": null
  },
  {
    "name": "C-algorithm",
    "description": null,
    "language": "C",
    "updatedAt": "2024-04-20",
    "isPrivate": true,
    "stars": 0,
    "url": null,
    "homepage": null
  },
  {
    "name": "machine-learning-helper",
    "description": "the function or docs that i made so i dont need to surfe so many docs website to build a model again",
    "language": "Jupyter Notebook",
    "updatedAt": "2024-03-13",
    "isPrivate": false,
    "stars": 1,
    "url": "https://github.com/kittyofheaven/machine-learning-helper",
    "homepage": null
  },
  {
    "name": "valentine-hana",
    "description": null,
    "language": "TypeScript",
    "updatedAt": "2024-02-13",
    "isPrivate": true,
    "stars": 0,
    "url": null,
    "homepage": "https://meng-valentine.vercel.app"
  },
  {
    "name": "learnUIKit",
    "description": null,
    "language": "Swift",
    "updatedAt": "2024-01-28",
    "isPrivate": false,
    "stars": 0,
    "url": "https://github.com/kittyofheaven/learnUIKit",
    "homepage": null
  },
  {
    "name": "Face-Recognition-SwiftUI",
    "description": null,
    "language": "Swift",
    "updatedAt": "2024-01-25",
    "isPrivate": false,
    "stars": 0,
    "url": "https://github.com/kittyofheaven/Face-Recognition-SwiftUI",
    "homepage": null
  },
  {
    "name": "simple-iOS-roullete-game",
    "description": null,
    "language": "Swift",
    "updatedAt": "2024-01-25",
    "isPrivate": false,
    "stars": 0,
    "url": "https://github.com/kittyofheaven/simple-iOS-roullete-game",
    "homepage": null
  },
  {
    "name": "PKM2024remotePPG",
    "description": null,
    "language": "Python",
    "updatedAt": "2024-01-15",
    "isPrivate": true,
    "stars": 0,
    "url": null,
    "homepage": null
  },
  {
    "name": "isr_extractor_BOTCampKemkominfo",
    "description": null,
    "language": "TypeScript",
    "updatedAt": "2024-01-05",
    "isPrivate": false,
    "stars": 0,
    "url": "https://github.com/kittyofheaven/isr_extractor_BOTCampKemkominfo",
    "homepage": "https://isr-extractor-bot-camp-kemkominfo.vercel.app"
  },
  {
    "name": "DayForge",
    "description": null,
    "language": "Swift",
    "updatedAt": "2024-01-03",
    "isPrivate": false,
    "stars": 0,
    "url": "https://github.com/kittyofheaven/DayForge",
    "homepage": null
  },
  {
    "name": "oop-swift",
    "description": null,
    "language": "Swift",
    "updatedAt": "2023-12-27",
    "isPrivate": true,
    "stars": 0,
    "url": null,
    "homepage": null
  },
  {
    "name": "ToDoList",
    "description": "Swift To Do List",
    "language": "Swift",
    "updatedAt": "2023-12-23",
    "isPrivate": false,
    "stars": 0,
    "url": "https://github.com/kittyofheaven/ToDoList",
    "homepage": null
  },
  {
    "name": "carshop",
    "description": null,
    "language": "CSS",
    "updatedAt": "2023-12-19",
    "isPrivate": false,
    "stars": 0,
    "url": "https://github.com/kittyofheaven/carshop",
    "homepage": null
  },
  {
    "name": "Final-Project-Dasprog",
    "description": null,
    "language": "C",
    "updatedAt": "2023-11-16",
    "isPrivate": true,
    "stars": 0,
    "url": null,
    "homepage": null
  },
  {
    "name": "Bom-Bom-Bakudan",
    "description": "Final Project Praktikum Dasar Pemrograman",
    "language": null,
    "updatedAt": "2023-11-16",
    "isPrivate": false,
    "stars": 0,
    "url": "https://github.com/kittyofheaven/Bom-Bom-Bakudan",
    "homepage": null
  },
  {
    "name": "zodiac",
    "description": "Zodiac calculator",
    "language": null,
    "updatedAt": "2023-11-13",
    "isPrivate": true,
    "stars": 0,
    "url": null,
    "homepage": null
  },
  {
    "name": "Belajar-Express",
    "description": null,
    "language": null,
    "updatedAt": "2023-09-07",
    "isPrivate": true,
    "stars": 0,
    "url": null,
    "homepage": null
  },
  {
    "name": "Webcam-Stress-Meter",
    "description": "An AI that can calculate your heart rate, emotions, and stress only with your webcam. You can use this app to replace pomodoro timer. So when the stress meter is high enough, you can just take a rest!",
    "language": "Jupyter Notebook",
    "updatedAt": "2023-08-01",
    "isPrivate": true,
    "stars": 0,
    "url": null,
    "homepage": null
  },
  {
    "name": "Real-Truth-or-Dare",
    "description": "Creating real truth or dare experience with web based lie detector",
    "language": "Jupyter Notebook",
    "updatedAt": "2023-08-01",
    "isPrivate": false,
    "stars": 3,
    "url": "https://github.com/kittyofheaven/Real-Truth-or-Dare",
    "homepage": null
  },
  {
    "name": "pythonxnext-todo-app",
    "description": null,
    "language": null,
    "updatedAt": "2023-07-31",
    "isPrivate": true,
    "stars": 0,
    "url": null,
    "homepage": null
  },
  {
    "name": "simple-relate-connect",
    "description": "this is the simple version of relate connect that hopefully will be published soon",
    "language": "TypeScript",
    "updatedAt": "2023-07-26",
    "isPrivate": false,
    "stars": 0,
    "url": "https://github.com/kittyofheaven/simple-relate-connect",
    "homepage": "https://simple-relate-connect.vercel.app"
  },
  {
    "name": "learn-typescript",
    "description": null,
    "language": "TypeScript",
    "updatedAt": "2023-07-26",
    "isPrivate": true,
    "stars": 0,
    "url": null,
    "homepage": null
  },
  {
    "name": "relate_connect",
    "description": "Many young people dive straight into dating w/o knowing anything. And let me tell you, 7 out of 10 relationship ended because of it. Well RelateConnect is ready to make your next relationship amazing.",
    "language": "JavaScript",
    "updatedAt": "2023-07-26",
    "isPrivate": false,
    "stars": 1,
    "url": "https://github.com/kittyofheaven/relate_connect",
    "homepage": null
  },
  {
    "name": "belajar-next-2",
    "description": null,
    "language": "JavaScript",
    "updatedAt": "2023-07-11",
    "isPrivate": true,
    "stars": 0,
    "url": null,
    "homepage": null
  },
  {
    "name": "belajar-next",
    "description": "gw belajar next js",
    "language": "JavaScript",
    "updatedAt": "2023-07-09",
    "isPrivate": true,
    "stars": 0,
    "url": null,
    "homepage": null
  },
  {
    "name": "indonesian-hangman",
    "description": "hangman built in python with indonesian language",
    "language": "Python",
    "updatedAt": "2023-06-22",
    "isPrivate": false,
    "stars": 0,
    "url": "https://github.com/kittyofheaven/indonesian-hangman",
    "homepage": null
  },
  {
    "name": "smada-fiesta-web",
    "description": "buat smadafiesta 2k22",
    "language": "HTML",
    "updatedAt": "2023-01-31",
    "isPrivate": false,
    "stars": 0,
    "url": "https://github.com/kittyofheaven/smada-fiesta-web",
    "homepage": null
  },
  {
    "name": "DigiSpark-Scripts",
    "description": "USB Rubber Ducky type scripts written for the DigiSpark.",
    "language": "C++",
    "updatedAt": "2022-11-22",
    "isPrivate": false,
    "stars": 0,
    "url": "https://github.com/kittyofheaven/DigiSpark-Scripts",
    "homepage": null
  },
  {
    "name": "email-date-automation",
    "description": "uhh dunno",
    "language": "Python",
    "updatedAt": "2022-06-28",
    "isPrivate": true,
    "stars": 0,
    "url": null,
    "homepage": null
  },
  {
    "name": "learn-python",
    "description": "just learn python repo in my language",
    "language": "Python",
    "updatedAt": "2022-05-28",
    "isPrivate": false,
    "stars": 0,
    "url": "https://github.com/kittyofheaven/learn-python",
    "homepage": null
  },
  {
    "name": "sleepsearch-backend",
    "description": null,
    "language": "Jupyter Notebook",
    "updatedAt": "2022-01-09",
    "isPrivate": true,
    "stars": 0,
    "url": null,
    "homepage": null
  },
  {
    "name": "deep_query",
    "description": null,
    "language": "Python",
    "updatedAt": "2021-12-14",
    "isPrivate": true,
    "stars": 0,
    "url": null,
    "homepage": null
  },
  {
    "name": "learn-docker",
    "description": "lerning doker",
    "language": "Python",
    "updatedAt": "2021-12-09",
    "isPrivate": true,
    "stars": 0,
    "url": null,
    "homepage": null
  },
  {
    "name": "shiro_api",
    "description": null,
    "language": "Python",
    "updatedAt": "2021-12-07",
    "isPrivate": true,
    "stars": 0,
    "url": null,
    "homepage": null
  },
  {
    "name": "idea-chart",
    "description": "my business idea or smthn from diagrams.net",
    "language": null,
    "updatedAt": "2021-11-25",
    "isPrivate": true,
    "stars": 0,
    "url": null,
    "homepage": null
  },
  {
    "name": "learn-tensorflow",
    "description": "just me learning deeplearning using tensor flow",
    "language": "Jupyter Notebook",
    "updatedAt": "2021-11-11",
    "isPrivate": true,
    "stars": 0,
    "url": null,
    "homepage": null
  },
  {
    "name": "learn-django",
    "description": "learn django with my language ofc",
    "language": "Python",
    "updatedAt": "2021-11-11",
    "isPrivate": true,
    "stars": 0,
    "url": null,
    "homepage": null
  },
  {
    "name": "web_blog",
    "description": null,
    "language": "HTML",
    "updatedAt": "2021-11-02",
    "isPrivate": true,
    "stars": 0,
    "url": null,
    "homepage": null
  },
  {
    "name": "flask_tutor",
    "description": "learning flask in my language",
    "language": "HTML",
    "updatedAt": "2021-11-02",
    "isPrivate": true,
    "stars": 0,
    "url": null,
    "homepage": null
  },
  {
    "name": "learn_sqlalchemy",
    "description": "learn sqlite3 with sqlalchemy",
    "language": "Python",
    "updatedAt": "2021-10-31",
    "isPrivate": true,
    "stars": 0,
    "url": null,
    "homepage": null
  },
  {
    "name": "vivy_AI",
    "description": "some simple ai, her name is vivy, but i think she's still broken HAHAHAHAHA",
    "language": "Python",
    "updatedAt": "2021-10-22",
    "isPrivate": false,
    "stars": 0,
    "url": "https://github.com/kittyofheaven/vivy_AI",
    "homepage": null
  },
  {
    "name": "flask_digit_recog",
    "description": null,
    "language": "Python",
    "updatedAt": "2021-10-20",
    "isPrivate": true,
    "stars": 0,
    "url": null,
    "homepage": null
  },
  {
    "name": "digit_recognition",
    "description": "digit recognition with tensorflow",
    "language": "Python",
    "updatedAt": "2021-10-20",
    "isPrivate": false,
    "stars": 0,
    "url": "https://github.com/kittyofheaven/digit_recognition",
    "homepage": null
  },
  {
    "name": "hashpy-bruteforce",
    "description": "SHA1 & MD5 pass bruteforcer built in python",
    "language": "Python",
    "updatedAt": "2021-10-18",
    "isPrivate": false,
    "stars": 0,
    "url": "https://github.com/kittyofheaven/hashpy-bruteforce",
    "homepage": null
  },
  {
    "name": "Tetra-Reboot",
    "description": "command line game (still not finished)",
    "language": "Python",
    "updatedAt": "2021-10-09",
    "isPrivate": false,
    "stars": 0,
    "url": "https://github.com/kittyofheaven/Tetra-Reboot",
    "homepage": null
  },
  {
    "name": "Shiro-Assistant",
    "description": "discord bot assitant",
    "language": "Python",
    "updatedAt": "2021-10-09",
    "isPrivate": true,
    "stars": 0,
    "url": null,
    "homepage": null
  },
  {
    "name": "Python_TicTacToe",
    "description": "tic tac toe built in python",
    "language": "Python",
    "updatedAt": "2021-10-05",
    "isPrivate": false,
    "stars": 0,
    "url": "https://github.com/kittyofheaven/Python_TicTacToe",
    "homepage": null
  },
  {
    "name": "To-Do-App",
    "description": "basic to do app built in django",
    "language": "Python",
    "updatedAt": "2021-09-18",
    "isPrivate": false,
    "stars": 0,
    "url": "https://github.com/kittyofheaven/To-Do-App",
    "homepage": null
  },
  {
    "name": "Hangman-Python",
    "description": "UwU, I'm a noob, so I made a command line game  ^_^",
    "language": "Python",
    "updatedAt": "2021-09-09",
    "isPrivate": false,
    "stars": 0,
    "url": "https://github.com/kittyofheaven/Hangman-Python",
    "homepage": null
  },
  {
    "name": "javascript-working-clock",
    "description": "javascript working clock my version",
    "language": "JavaScript",
    "updatedAt": "2021-09-09",
    "isPrivate": false,
    "stars": 0,
    "url": "https://github.com/kittyofheaven/javascript-working-clock",
    "homepage": null
  },
  {
    "name": "hello-world",
    "description": "my first github repo",
    "language": null,
    "updatedAt": "2021-09-08",
    "isPrivate": true,
    "stars": 0,
    "url": null,
    "homepage": null
  }
];
